---
kind: pipeline
type: docker
name: xenial

steps:
- name: submodule
  image: drone/git
  commands:
  - git submodule update --init

- name: test
  image: ubuntu:xenial
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make python3 xvfb sudo git gnupg
  - scripts/deps.py install -- -y
  - ln -s /usr/include/libcxxabi/__cxxabi_config.h /usr/include/c++/v1/

  - scripts/set-version $(git describe --tags HEAD)
  - ./configure
  - make build
  - make smoke-test

---
kind: pipeline
type: docker
name: focal

steps:
- name: submodule
  image: drone/git
  commands:
  - git submodule update --init

- name: test
  image: ubuntu:focal
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make python3 xvfb sudo git gnupg
  - scripts/deps.py install -- -y

  - scripts/set-version $(git describe --tags HEAD)
  - ./configure
  - make build
  - make smoke-test

---
kind: pipeline
type: docker
name: raspi

platform:
  os: linux
  arch: arm

steps:
- name: submodule
  image: drone/git
  commands:
  - git submodule update --init

- name: test
  # buster armhf (default is armel)
  image: debian@sha256:43e8691b4e25f4b0fd0f10bca8ea11b9f0578b0e5d2fe3b085290455dd07c0b6
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends make python3 xvfb sudo git gnupg
  - scripts/deps.py install -- -y

  - scripts/set-version $(git describe --tags HEAD)
  - ./configure
  - make build
  - make smoke-test

---
kind: pipeline
type: docker
name: wine

steps:
- name: submodule
  image: drone/git
  commands:
  - git submodule update --init

- name: test
  image: ubuntu:focal
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt-get update
  - apt-get install -y --no-install-recommends gnupg
  - echo deb http://apt.arescentral.org focal contrib | tee /etc/apt/sources.list.d/arescentral.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv 5A4F5210FF46CEE4B799098BAC879AADD5B51AE9

  - apt-get update
  - apt-get install -y --no-install-recommends build-essential clang make python3 git mingw-w64 xvfb wine-stable gn ninja-build

  - scripts/set-version $(git describe --tags HEAD)
  - ./configure -o win
  - make build
  - make test-wine

...
