language:  cpp

env:
  - TESTS=test

matrix:
  include:
    - os:         osx
      osx_image:  xcode9.2
      env:
        - TESTS=smoke-test  # Need to figure out headless CGLPixelFormatObj

    - os:       linux
      dist:     xenial
      install:  sudo make install-deps

# Recursive submodules are unnecessary and wasteful in Antares.
# Manually check out non-recursive submodules.
git:
  submodules: false
before_install:
  - git submodule update --init

script: ./configure && make && make $TESTS
