language:  cpp

matrix:
  include:
    - os:         osx
      osx_image:  xcode12u

      install:
        - scripts/load-cert.sh
        - brew update
        - brew unlink python@3.8  # temporary until Travis image defaults to 3.9?
        - HOMEBREW_VERBOSE_USING_DOTS=true scripts/deps.py install -- -v

      script:
        - CPPFLAGS='-isysroot /Applications/Xcode-12.for.macOS.Universal.Apps.beta.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' LDFLAGS='-isysroot /Applications/Xcode-12.for.macOS.Universal.Apps.beta.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' ./configure --antares-version=$(git describe --tags HEAD)
        - make build
        - make smoke-test

      before_deploy:
        - make dist
        - make macdist

      deploy:
        provider:       gcs
        skip_cleanup:   true
        access_key_id:  GOOG5V7J5HCR4SRF4YCUI7EL
        secret_access_key:
          secure: BSha8nkjJqEnsqW12HZshAs00Q8BKniDhJ7W94ecbYMxm7ZKcTWIVGZ1I8r+1TmgFFXaqxaTYEvQ7Ga7GUfdon9ow2zq9Z/T6nsCYIYax7pXuc2mWk8ndX504dTLue72XhXRlXIUvqJyIAAips8cIsSybnt1KKOlYuoAcNonQtY=
        bucket:      downloads.arescentral.org
        local-dir:   dist
        upload-dir:  Antares
        on:
          all_branches: true
          condition: ( "$TRAVIS_BRANCH" = master ) || ( -n "$TRAVIS_TAG" )


# Recursive submodules are unnecessary and wasteful in Antares.
# Manually check out non-recursive submodules.
git:
  submodules: false
before_install:
  - git submodule update --init
