language:  cpp

matrix:
  include:
    - os:         osx
      osx_image: xcode11.5

      install:
        - scripts/load-cert.sh

      script:
        - scripts/set-version $(git describe --tags HEAD)
        - ./configure
        - make build
        - make smoke-test

      before_deploy:
        - make dist
        - make macdist

      deploy:
        provider:       gcs
        skip_cleanup:   true
        access_key_id:  GOOG5V7J5HCR4SRF4YCUI7EL
        secret_access_key:
          secure: BSha8nkjJqEnsqW12HZshAs00Q8BKniDhJ7W94ecbYMxm7ZKcTWIVGZ1I8r+1TmgFFXaqxaTYEvQ7Ga7GUfdon9ow2zq9Z/T6nsCYIYax7pXuc2mWk8ndX504dTLue72XhXRlXIUvqJyIAAips8cIsSybnt1KKOlYuoAcNonQtY=
        bucket:      downloads.arescentral.org
        local-dir:   dist
        upload-dir:  Antares
        on:
          all_branches:  true

    - os:       linux
      dist:     xenial

      install:
        - sudo apt-get update
        - sudo scripts/installdeps.py

      script:
        - scripts/set-version $(git describe --tags HEAD)
        - ./configure
        - make build
        - make smoke-test
        - make test-install

    - os:        linux
      services:
        - docker
      before_install:
        - git submodule update --init
        - docker run -d --name wine -v $(pwd):/antares -w /antares ubuntu:focal sleep infinity
        - docker ps

      install:
        - $SH apt-get update
        - $SH apt-get install -y --no-install-recommends build-essential clang make python3
        - $SH apt-get install -y --no-install-recommends mingw-w64 xvfb wine-stable

      script:
        - $SH scripts/set-version $(git describe --tags HEAD)
        - $SH ./configure -owin
        - $SH make build
        - $SH make test-wine

      env:
        - SH="docker exec -e DEBIAN_FRONTEND=noninteractive wine"

# Recursive submodules are unnecessary and wasteful in Antares.
# Manually check out non-recursive submodules.
git:
  submodules: false
before_install:
  - git submodule update --init
