language:  cpp

matrix:
  include:
    - os:  osx

    - os:    linux
      dist:  trusty
      addons:
        apt:
          packages:
            - clang
            - pkg-config

            - libgl1-mesa-dev
            - libglfw3-dev
            - libglu1-mesa-dev
            - libmodplug-dev
            - libzip-dev
            - libpng16-dev
            - libneon27-dev
            - libopenal-dev
            - libsndfile1-dev
            - libx11-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - libxxf86vm-dev
            - zlib1g-dev

