language:  cpp

env:
  - TESTS=test

matrix:
  include:
    - os:         osx
      env:
        - TESTS=travis-test-mac

    - os:       linux
      group:    edge
      dist:     xenial
      install:  sudo scripts/installdeps.py
      env:
        - TESTS=travis-test-linux

# Recursive submodules are unnecessary and wasteful in Antares.
# Manually check out non-recursive submodules.
git:
  submodules: false
before_install:
  - git submodule update --init

script: ./configure && make && make $TESTS
