#!/usr/bin/env python

import contextlib
import shutil
import subprocess
import sys
import tempfile

def main():
    args = sys.argv[1:]
    name = args.pop(0)
    expected = "test/%s" % name

    with NamedTemporaryDir() as dir:
        antares_command = ["out/cur/%s" % name] + args + ["--output=%s" % dir]
        antares = subprocess.Popen(antares_command)
        antares.communicate()
        assert antares.returncode == 0, "Antares failed"

        diff_command = ["diff", "-ru", "-x.*", expected, dir]
        diff = subprocess.Popen(diff_command)
        diff.communicate()
        assert diff.returncode == 0, "diff failed"

@contextlib.contextmanager
def NamedTemporaryDir():
    dir = tempfile.mkdtemp()
    try:
        yield dir
    finally:
        shutil.rmtree(dir)

if __name__ == "__main__":
    main()
