#!/usr/bin/env python3

import os
import sys
import tempfile
import urllib.request
import zipfile


def main():
    for arg in sys.argv[1:]:
        url, file = arg.rsplit(":", 1)
        with tempfile.TemporaryDirectory() as tmp:
            zip_path = os.path.join(tmp, "archive.zip")
            urllib.request.urlretrieve(url, zip_path)
            with zipfile.ZipFile(zip_path) as z:
                z.extract(file)
            print(file)


if __name__ == "__main__":
    main()
