#!/bin/bash
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

set -o errexit

if [[ -z "$ANTARES" ]]; then
    echo >&2 'must set $ANTARES'
    exit 1
fi
cd $ANTARES

# Allow paths to utilities to be provided; use /usr/bin as default.
GIT=${GIT-/usr/bin/git}
ZIP=${ZIP-/usr/bin/zip}
GSUTIL=${GSUTIL-/usr/bin/gsutil}

# Ensure that we are building from a clean and up-to-date checkout of
# the "master" branch.  Remove untracked files.
$GIT checkout master
$GIT reset --hard master
$GIT pull
$GIT submodule init
$GIT submodule update
$GIT clean -f

# Build Antares.  Note that we don't make any attempt to clean the
# working directory before we build.
./configure --mode=opt "$@"
make

# Zip the product of the build.
cd out/cur
rm -f Antares-nightly.zip
$ZIP -r Antares-nightly.zip Antares.app

# Copy to downloads.arescentral.org.
$GSUTIL cp Antares-nightly.zip gs://downloads.arescentral.org/Antares/Antares-nightly.zip
echo "done"
