#!/usr/bin/env python3
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

import os
import subprocess

APP = "out/cur/Antares.app"
KEYCHAIN = "build.keychain"
PROFILE = "notary"


def main():
    username = os.getenv("APPLE_USER")
    password = os.getenv("APPLE_PASS")
    team_id = os.getenv("APPLE_TEAM")
    assert username
    assert password
    assert team_id

    store_credentials(username, password, team_id)
    submit()
    staple()


def store_credentials(username, password, team_id):
    subprocess.run(
        ["xcrun", "notarytool", "store-credentials", PROFILE]
        + ["--apple-id", username]
        + ["--password", password]
        + ["--team-id", team_id]
        + ["--keychain", KEYCHAIN],
        check=True,
    )


def submit():
    subprocess.run(
        ["xcrun", "notarytool", "submit", APP]
        + ["--keychain-profile", PROFILE]
        + ["--keychain", KEYCHAIN]
        + ["--wait"],
        check=True,
    )


def staple():
    subprocess.run(
        ["xcrun", "stapler", "staple", APP],
        check=True,
    )


if __name__ == "__main__":
    main()
