#!/usr/bin/env zsh
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

if [[ $# != 2 ]]; then
    echo >&2 "usage: $(basename $0) encode MESSAGE_TYPE"
    echo >&2 "       $(basename $0) encode MESSAGE_TYPE"
    exit 64
fi

protoc --$1=$2 proto/*
