#!/bin/zsh

set -o errexit

progname=$(basename $0)
usage() {
    echo >&2 "usage: $progname start VERSION"
    echo >&2 "       $progname finish VERSION"
    exit 1
}

if [[ $# != 2 ]]; then
    usage
fi

# Check that there is a line 'VERSION = "..."' in the gn file.
grep >/dev/null '^  antares_version = ".*"$' BUILD.gn
ACTION=$1
VERSION=$2

if [[ $1 = start ]]; then
    if [[ $(git rev-parse HEAD) != $(git rev-parse master) ]]; then
        echo >&2 "must be on master"
        exit 1
    fi
elif [[ $1 = finish ]]; then
    if [[ $(git rev-parse HEAD) != $(git rev-parse release/$VERSION) ]]; then
        echo >&2 "must be on release/$VERSION"
        exit 1
    fi
else
    usage
fi

update-gn() {
    sed -i '' 's/  antares_version = ".*"/  antares_version = "'$1'"/' BUILD.gn
}

update-readme() {
    sed -i '' 's/\(Antares[- ]\)\([0-9.]*\)[0-9]/\1'$1'/g' README.rst
}

if [[ $ACTION == start ]]; then
    set -o verbose
    git checkout -b release/$VERSION
    update-gn ${VERSION}~rc1
    git commit BUILD.gn README.rst -m "Create release branch for $VERSION."
else
    set -o verbose
    update-gn $VERSION
    update-readme $VERSION
    git commit BUILD.gn README.rst -m "Release Antares $VERSION."

    git checkout stable
    git merge --no-ff release/$VERSION
    git tag v$VERSION
    ./configure --mode=opt
    make
    make sign
    (cd out/cur && zip -r ../../Antares-$VERSION.zip Antares.app)
    scripts/dist.py zip
    scripts/dist.py gz
    scripts/dist.py bz2

    git checkout master
    git merge --no-ff release/$VERSION
fi
