#!/bin/zsh
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

set -o errexit

progname=$(basename $0)
usage() {
    echo >&2 "usage: $progname start VERSION"
    echo >&2 "       $progname finish VERSION"
    exit 1
}

if [[ $# != 2 ]]; then
    usage
fi

# Check that there is a line 'VERSION = "..."' in the gn file.
grep >/dev/null '^  antares_version = ".*"$' BUILD.gn
ACTION=$1
VERSION=$2

if [[ $1 = start ]]; then
    if [[ $(git rev-parse HEAD) != $(git rev-parse master) ]]; then
        echo >&2 "must be on master"
        exit 1
    fi
elif [[ $1 = finish ]]; then
    if [[ $(git rev-parse HEAD) != $(git rev-parse release/$VERSION) ]]; then
        echo >&2 "must be on release/$VERSION"
        exit 1
    fi
else
    usage
fi

update-readme() {
    sed 's/\(Antares[- ]\)\([0-9.]*\)[0-9]/\1'$1'/g' README.rst >.README.rst.tmp
    mv .README.rst.tmp README.rst
}

if [[ $ACTION == start ]]; then
    set -o verbose
    git checkout -b release/$VERSION
    scripts/set-version ${VERSION}~rc1
    git commit BUILD.gn README.rst -m "Create release branch for $VERSION."
else
    set -o verbose
    scripts/set-version $VERSION
    update-readme $VERSION
    git commit BUILD.gn README.rst -m "Release Antares $VERSION."

    git checkout stable
    git merge --no-ff release/$VERSION
    git tag v$VERSION
fi
