#!/bin/bash
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

set -o errexit
set -o nounset

gsutil cp "$@" gs://downloads.arescentral.org/Antares/
