#!/bin/zsh
# Copyright (C) 2017 The Antares Authors
# This file is part of Antares, a tactical space combat game.
# Antares is free software, distributed under the LGPL+. See COPYING.

ls test/*.NLRP | sed 's,test/\(.*\)\.NLRP,\1,' | xargs $@
